### ISSUE TITLE
How to prepare the raw data of KITTI?

### ISSUE THREAD

**Issue by jichaofeng** [Tai-Wang/Depth-from-Motion#10]
Thank you for sharing your code. Should we download the raw data for all the categories (city, residential,road campus,person)from http://www.cvlibs.net/datasets/kitti/raw_data.php?  There are so many files. Can we download the raw data from http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d and click this link (3 temporally preceding frames (left colour)(36 GB))?

**Comment by Tai-Wang** [comment]
Just downloading the data in the 3D detection benchmark is OK. Necessary information from raw data has been attached in this project. You can follow the [instructions from mmdet3d](https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html#kitti) to prepare the basic data for 3D detection on KITTI. The only differences are presented [here](https://github.com/Tai-Wang/Depth-from-Motion#data-preparation).

**Comment by xiaowenhe** [comment]
Where can I get prev_2 folder and *png in this folder?

**Comment by jichaofeng** [comment]
You can download prev_2 from KITTI website,https://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d
