### ISSUE TITLE
some error when running mono_det_demo.py

### ISSUE THREAD

**Issue by jichaofeng** [Tai-Wang/Depth-from-Motion#11]
we run mono_det_demo.py following this instruction:python demo/mono_det_demo.py demo/data/kitti/000008.png demo/data/kitti/kitti_000008_infos.pkl configs/dfm/dfm_r34_1x8_kitti-3d-3class.py checkpoints/dfm.pth
FileNotFoundError: [Errno 2] No such file or derectory: 'demo/data/kitti/00008_03.png'
the basic data for 3D detection on KITTI does not contain the image named 00008_03.png, what should I do?

**Comment by Tai-Wang** [comment]
Sorry, I find due to the gitignore setting, the demo-related files were not updated before. You can have a try by checking out the latest main branch.

**Comment by jichaofeng** [comment]
`[yyyyyyy](url)`

**Comment by Tai-Wang** [comment]
prev_2 files can be downloaded from [the official website](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d).

**Comment by jichaofeng** [comment]
Thank you!
