### ISSUE TITLE
关于RandomCrop3D实现的问题

### ISSUE THREAD

**Issue by shuowang666** [Tai-Wang/Depth-from-Motion#14]
![image](https://user-images.githubusercontent.com/56186807/190333476-968080f2-7085-4fa3-b2ee-f7bac77a89c2.png)
请问一下这里增加一个矩阵T的作用是什么啊？我的理解T就是单位阵，这个T看起来有点多余？还是我哪里没有理解到位呢？另外，offset_cam2img和K貌似也是一样？

**Comment by Tai-Wang** [comment]
可以参考 KITTI [原文](https://www.cvlibs.net/publications/Geiger2013IJRR.pdf)，因为这个投影矩阵 cam2img 包含了当前 cam 和 calibrated reference cam 之间的 offset，所以这里的第四列（cam2img[:, 3]）不全都是0；这里是为了保证 crop 对投影矩阵做 manipulation 的时候不受那部分的影响。
