### ISSUE TITLE
compute_detection_let_metrics_main细节

### ISSUE THREAD

**Issue by shuowang666** [Tai-Wang/Depth-from-Motion#16]
您好，如果想了解LET-AP计算的细节，该去哪里查看代码呢？您提供的这个compute_detection_let_metrics_main文件是waymo官方提供的还是您自己写的呢？

**Comment by Tai-Wang** [comment]
请参考更新的 [FAQ](https://github.com/Tai-Wang/Depth-from-Motion#faq) 内容。
