### ISSUE TITLE
Indoor object detection on the way?

### ISSUE THREAD

**Issue by ChiyuanFeng** [Tai-Wang/Depth-from-Motion#17]
Hello Wang Tai,
Great work and thanks for releasing this contribution.As I can see the data dir includes indoor dataset like scannet. Have you tried this on indoor scenario?

**Comment by Tai-Wang** [comment]
Please refer to [ImVoxelNet](https://github.com/saic-vul/imvoxelnet) and [mmdet3d](https://github.com/open-mmlab/mmdetection3d) for some basic indoor methods. Further exploration in this direction is ongoing and please stay tuned.
