### ISSUE TITLE
where to get waymo/kitti_format/ImageSets/test_cam_only.txt?

### ISSUE THREAD

**Issue by synsin0** [Tai-Wang/Depth-from-Motion#19]
Thanks for sharing camera-only pipeline for waymo dataset. where to get waymo/kitti_format/ImageSets/test_cam_only.txt?

**Comment by Tai-Wang** [comment]
Sorry for the late reply. There is my previously used [.txt file](https://download.openmmlab.com/mim-example/dfm/dfm_r34_1x8_kitti-3d-3class/test_cam_only.txt) just for your reference. I used the "3" as the prefix to represent the camera_only test set split to distinguish it from the original test set for lidar-based 3d detection. You can also simply adjust it for your own convenience.
