### ISSUE TITLE
无法训练

### ISSUE THREAD

**Issue by le-cheng** [Tai-Wang/Depth-from-Motion#2]
我该如何使用你的代码和脚本在自己的服务器训练

**Comment by Tai-Wang** [comment]
KITTI 部分因为代码进行了重构，近期还在抽时间对训练精度，目前还稍微有些不稳定，待完全对齐会更新当前 readme，以及 release 全部 config/models。
Waymo 部分或许可以先尝试着跑一下，有什么问题可以反馈，应该 PGD 和 MV-FCOS3D++ 的 config 都是能够跑通的。不过数据预处理部分还没有仔细整理和验证过，我尽量在月底之前完成验证。

**Comment by Tai-Wang** [comment]
Hi @le-cheng，近期对项目内容进行了初步更新，可以尝试用最新的代码和配置文件跑下试试，如有问题欢迎再来提相应的 issue。
