### ISSUE TITLE
About the checkpoint of FCOS++

### ISSUE THREAD

**Issue by toyot-li** [Tai-Wang/Depth-from-Motion#20]
Hi, @Tai-Wang thanks for your work. The MV-FCOS3D++ cfg includes the pre-trained checkpoint https://github.com/Tai-Wang/Depth-from-Motion/blob/main/configs/dfm/multiview-dfm_r101_dcn_2x16_waymoD5-3d-3class_camsync_10sweeps.py#L247 as a prerequisite, but it is not provided, unfortunately.

So I would like to ask how to train the model and get this checkpoint by myself. More specifically, the tech report https://arxiv.org/abs/2207.12716 emphasized FCOS3D++ is trained with *only object annotations*. I'm not clear what is the difference from the original FCOS3D, by emphasizing this. All in all, would you mind explaining more about the training of FCOS3D++, in favor of the re-implementation of MV-FCOS3D++ by myself? Thanks.

**Comment by Tai-Wang** [comment]
You can basically use the [config](https://github.com/Tai-Wang/Depth-from-Motion/blob/main/configs/pgd/pgd_r101_fpn_gn-head_dcn_3x16_2x_waymoD3-mv3d.py) provided here to reproduce the training of FCOS3D++.

**Comment by Tai-Wang** [comment]
I emphasize the training only involves object annotations to clarify that our model does not need any depth pretraining or LiDAR data as depth supervision. This detail is the same for the original FCOS3D and FCOS3D++/PGD.

**Comment by toyot-li** [comment]
@Tai-Wang Thanks for your reply, but I find the cfg you referred to still includes a depth regression https://github.com/Tai-Wang/Depth-from-Motion/blob/main/configs/pgd/pgd_r101_fpn_gn-head_dcn_3x16_2x_waymoD3-mv3d.py#L33, am I missing anything?

**Comment by Tai-Wang** [comment]
The depth regression is only set for each instance's center. We do not involve dense depth estimation supervised by dense depth map or projected LiDAR points map.
