### ISSUE TITLE
Can't inference with pretrained model

### ISSUE THREAD

**Issue by PhanThanhTrung** [Tai-Wang/Depth-from-Motion#3]
Hello, I'm interested in your work and I'm trying to see how your work performs on my test data.
* I followed every step in the Installation part on README [here](https://github.com/Tai-Wang/Depth-from-Motion/blob/main/README.md#installation). 
* I downloaded the pre-trained model from the link you provided [here](https://github.com/Tai-Wang/Depth-from-Motion/blob/main/README.md#dfm). 
* I tried to infer an image using the pre-trained model and provided configuration by running `mono_det_demo.py`, but It seems like I loaded the wrong config file cause there are some keys required in inference code that doesn't exist in the config file.
* Is that a bug or did I load the wrong config file? Is there any document describing how to infer an image with a known camera matrix?

**Comment by Tai-Wang** [comment]
Hi @PhanThanhTrung , thanks for your interest and feedback.

Sorry that this code release is still a draft version and there are many details to be fixed. I do not try the `mono_det_demo.py` after adding the new model based on mmdet3d, and there can be some bugs by directly running it in the conventional way. I will fix it ASAP after I preliminarily make sure the training is relatively stable after refactoring. Please stay tuned.

**Comment by PhanThanhTrung** [comment]
@Tai-Wang thanks for your response. I'm looking forward to you fixing it 💻💻💻💻

**Comment by Tai-Wang** [comment]
Hi @PhanThanhTrung , I have fixed the monocular 3D detection demo to make it compatible with DfM. Please try it following [this instruction](https://github.com/Tai-Wang/Depth-from-Motion#demo) :)
