### ISSUE TITLE
kitti数据集下如何完成训练？

### ISSUE THREAD

**Issue by wangluyabupt** [Tai-Wang/Depth-from-Motion#4]
您好，请问现在的代码是不是不能支持kitti上的训练呢？还是只是精度无法对齐呀？

**Comment by Tai-Wang** [comment]
我这两天再做下最后走通整个流程的验证，会在这周末前更新一版 code，请到时关注和试用~

**Comment by wangluyabupt** [comment]
感谢您更新的代码。有个问题想请教下，现在dfm_r34_1x8_kitti-3d-3class.py这个配置文件的模型依旧会让我的显存爆掉，请问有没有小一点的模型config可以参考呢？或者怎么样可以使得运行过程中把显存降下来

**Comment by Tai-Wang** [comment]
之前尝试过可以缩小 [num_bins](https://github.com/Tai-Wang/Depth-from-Motion/blob/main/configs/dfm/dfm_r34_1x8_kitti-3d-3class.py#L6) 到 96 可以少掉一些点，以及可以尝试去掉[这个地方](https://github.com/Tai-Wang/Depth-from-Motion/blob/main/configs/dfm/dfm_r34_1x8_kitti-3d-3class.py#L79)的 2d detection head；再进一步缩小的话可能需要把 voxelization 放到 CPU 上做会好些。总体上之前有缩到 12G 显存内，重构后还没时间尝试，过段时间我可以看看，在那之前你可以先尝试这几点试试看。

**Comment by wangluyabupt** [comment]
嗯嗯好的，感谢您的回复
