### ISSUE TITLE
nuScenes support

### ISSUE THREAD

**Issue by s-ryosky** [Tai-Wang/Depth-from-Motion#8]
Do you have a plan to support nuScenes dataset?

**Comment by Tai-Wang** [comment]
We have an ongoing project related to it and may consider supporting it afterward. For now, I know another [project](https://github.com/Megvii-BaseDetection/BEVStereo) from my friends closely related to ours that is released soon. You can refer to their implementation on nuScenes. It also leverages temporal stereo to achieve more accurate depth estimation and camera-only 3D detection.
