### ISSUE TITLE
Table 3.中Mono Only

### ISSUE THREAD

**Issue by wangluyabupt** [Tai-Wang/Depth-from-Motion#9]
请问测试Mono Only的话是否只需要改动这里：https://github.com/Tai-Wang/Depth-from-Motion/blob/main/mmdet3d/models/backbones/dfm_backbone.py#L141：
改动为：
**return cost -> return mono_cost1**

还有其他地方需要调整吗？

**Comment by Tai-Wang** [comment]
应该还需要把[这个地方](https://github.com/Tai-Wang/Depth-from-Motion/blob/main/mmdet3d/models/detectors/dfm.py#L317)输入从 stereo_feats 改成 mono_feats。不过因为 ablation 是在之前的 code 上做的，重构后想到的这两处也可能有所疏漏，你可以先试试看。

**Comment by wangluyabupt** [comment]
嗯嗯，上述也做过调整，可能我忽略了其他的细节

**Comment by Tai-Wang** [comment]
会报错么 还是结果不太符合预期

**Comment by wangluyabupt** [comment]
不会报错，但是相较于mono_feats而言，使用stereo_feats不会有论文ablation study中那样明显的涨幅，或许与num_bins=96有关？这里的num_bins为什么不会像常见的=2这样的数字呢？

**Comment by Tai-Wang** [comment]
可能是，num_bins=96 的设置上结果还挺不稳定的，另外我这边没有加 depth estimation 的 evaluation，你可以参考 LIGA-Stereo 加一下看看，可以先看下 depth estimation 指标上是不是有明显提升。

num_bins 是指在 depth 方向上划分 bin 的数量，这个数量会在 sample 的时候降采样 4 倍，也就是说真正预测的时候，num_bins=96 相当于只预测了 24 个 bin 的划分，这个和 288/4=72 个 bin 差别还是比较大的。如果采用更小的 num_bins，预测结果会更差。这个也和采用的 depth loss 有关，因为这里采用的是常见的类似分类的 loss，所以 bin 的划分还是要比较细致的，是不同于 PGD 里面的 probabilistic formulation 的。
